# Generated by Django 4.2.7 on 2024-03-10 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('is_good_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак приятной привычки')),
                ('periodic', models.CharField(choices=[('s', 'Single'), ('d', 'Daily'), ('w', 'Weekly'), ('m', 'Monthly')], default='d', max_length=1, verbose_name='периодичность')),
                ('lead_time', models.TimeField(blank=True, null=True, verbose_name='время выполнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичный')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='награда')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
